# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class A2acli < Formula
  desc "A standalone A2A v1.0 compliant command-line client"
  homepage "https://github.com/ghchinoy/a2acli"
  version "1.4.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ghchinoy/a2acli/releases/download/v1.4.2/a2acli_Darwin_x86_64.tar.gz"
      sha256 "9744ff619ff62e7f4e7c41321de61b530c0ee191fd7d84c77d1924a650758bb4"

      define_method(:install) do
        bin.install "a2acli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ghchinoy/a2acli/releases/download/v1.4.2/a2acli_Darwin_arm64.tar.gz"
      sha256 "31af76531208d70721881aa66a9125f91c47156caa24af211d4ee10079db3af0"

      define_method(:install) do
        bin.install "a2acli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghchinoy/a2acli/releases/download/v1.4.2/a2acli_Linux_x86_64.tar.gz"
      sha256 "e992bfe8020b16dc62c1384707b867bf0d22c7c9d654108c86a6e9d52b66a2f5"
      define_method(:install) do
        bin.install "a2acli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghchinoy/a2acli/releases/download/v1.4.2/a2acli_Linux_arm64.tar.gz"
      sha256 "f6fd21d1d5c564d8985847e5133eac64a940a3082f871a3c0294fabd11dbf00e"
      define_method(:install) do
        bin.install "a2acli"
      end
    end
  end

  test do
    system "#{bin}/a2acli", "--version"
  end
end
