# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class A2acli < Formula
  desc "A standalone A2A v1.0 compliant command-line client"
  homepage "https://github.com/ghchinoy/a2acli"
  version "1.4.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ghchinoy/a2acli/releases/download/v1.4.3/a2acli_Darwin_x86_64.tar.gz"
      sha256 "731b4f46cc237d388a30edf17d2d931baff26946cb1971877073fd59201c5507"

      define_method(:install) do
        bin.install "a2acli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ghchinoy/a2acli/releases/download/v1.4.3/a2acli_Darwin_arm64.tar.gz"
      sha256 "9587612d5a08dc8cdc2096fe040d4b49c1eb448eaf6317c1ccfa8dd87736beca"

      define_method(:install) do
        bin.install "a2acli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghchinoy/a2acli/releases/download/v1.4.3/a2acli_Linux_x86_64.tar.gz"
      sha256 "0a3b132a87c38f85a8c4807b1a04f1a34b895564ad2fe58a647b7d64515009c8"
      define_method(:install) do
        bin.install "a2acli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghchinoy/a2acli/releases/download/v1.4.3/a2acli_Linux_arm64.tar.gz"
      sha256 "bed3ba5761abe4138f746c79dace2ba2a22315f8df914857c60881ec89d1eb1e"
      define_method(:install) do
        bin.install "a2acli"
      end
    end
  end

  test do
    system "#{bin}/a2acli", "--version"
  end
end
