# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class A2acli < Formula
  desc "A standalone A2A v1.0 compliant command-line client"
  homepage "https://github.com/ghchinoy/a2acli"
  version "1.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ghchinoy/a2acli/releases/download/v1.5.0/a2acli_Darwin_x86_64.tar.gz"
      sha256 "adebce9d8187144b6621f17188df2e5ce81f31b9fccae9532498384900a9444f"

      define_method(:install) do
        bin.install "a2acli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ghchinoy/a2acli/releases/download/v1.5.0/a2acli_Darwin_arm64.tar.gz"
      sha256 "94f083746bb1b9c0a674e93cfbeab3ca633ba0bea05fea29e20a5916f7d4e415"

      define_method(:install) do
        bin.install "a2acli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghchinoy/a2acli/releases/download/v1.5.0/a2acli_Linux_x86_64.tar.gz"
      sha256 "e0d343d877b4697d038e25c8dcd3c0104eb79685d0e8e1c78e040fbe23f3c8e3"
      define_method(:install) do
        bin.install "a2acli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghchinoy/a2acli/releases/download/v1.5.0/a2acli_Linux_arm64.tar.gz"
      sha256 "0b6e061b5bebffe04b812f74ce057e5db638192dbdbac1b1652d13ccbbc5bab8"
      define_method(:install) do
        bin.install "a2acli"
      end
    end
  end

  test do
    system "#{bin}/a2acli", "--version"
  end
end
