# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Binder < Formula
  desc "Convert a plain-markdown corpus into a conformant OKF bundle"
  homepage "https://github.com/ghchinoy/binder"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ghchinoy/binder/releases/download/v0.1.0/binder_0.1.0_darwin_amd64.tar.gz"
      sha256 "ea0e6e71db1a40b2ff0b17a87e9ecf77ee8955773726cf32068b16a7da1f2abc"

      define_method(:install) do
        bin.install "binder"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ghchinoy/binder/releases/download/v0.1.0/binder_0.1.0_darwin_arm64.tar.gz"
      sha256 "4d347eacbe19ba4f17916492e75bde4d5ee6f89438421ebc9014e7559bdd3dfe"

      define_method(:install) do
        bin.install "binder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghchinoy/binder/releases/download/v0.1.0/binder_0.1.0_linux_amd64.tar.gz"
      sha256 "f1cc5db17a793b0037508a8cd0cb3f262b4aa79b849f46a3a99990da7ee90a69"
      define_method(:install) do
        bin.install "binder"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghchinoy/binder/releases/download/v0.1.0/binder_0.1.0_linux_arm64.tar.gz"
      sha256 "fb986c8d655572505c42b10e6d0ddb41725cca1840e2abf98a67be2c7f84c17a"
      define_method(:install) do
        bin.install "binder"
      end
    end
  end

  test do
    system "#{bin}/binder", "--version"
  end
end
