# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Binder < Formula
  desc "Convert a plain-markdown corpus into a conformant OKF bundle"
  homepage "https://github.com/ghchinoy/binder"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ghchinoy/binder/releases/download/v0.5.0/binder_0.5.0_darwin_amd64.tar.gz"
      sha256 "e9e317cc515d9e79fd5d57d7e38a4b9fc0ddbe4220e966cc6731c2f4a114386b"

      define_method(:install) do
        bin.install "binder"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ghchinoy/binder/releases/download/v0.5.0/binder_0.5.0_darwin_arm64.tar.gz"
      sha256 "a3f1c5dcd1c9f2122291f538d848f5d5a3b35c7fbe424c63d2d618452a925f45"

      define_method(:install) do
        bin.install "binder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghchinoy/binder/releases/download/v0.5.0/binder_0.5.0_linux_amd64.tar.gz"
      sha256 "5accc5ca4e651ec278f309ec050480f49f2cb1a3718a9f7f2f1bd70224d6fede"
      define_method(:install) do
        bin.install "binder"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghchinoy/binder/releases/download/v0.5.0/binder_0.5.0_linux_arm64.tar.gz"
      sha256 "e3f37347b2292c5cb30810167f50539d5ba4a237d8c05b1cacf4b07bd3c0c556"
      define_method(:install) do
        bin.install "binder"
      end
    end
  end

  test do
    system "#{bin}/binder", "--version"
  end
end
