# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Credentialctl < Formula
  desc "C2PA Content Credentials validation and inspection tool with interactive TUI"
  homepage "https://github.com/ghchinoy/credentialctl"
  version "0.1.1"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/ghchinoy/credentialctl/releases/download/v0.1.1/credentialctl_0.1.1_darwin_arm64.tar.gz"
    sha256 "37efc8dae7c8215690b55dbad9aac4f3979b5da7d40bef4ba93c1f7b70b4ddaa"

    define_method(:install) do
      bin.install "credentialctl"
      if OS.mac?
        lib.install "libcredentio_c.dylib"
      elsif OS.linux?
        lib.install "libcredentio_c.so"
      end
    end
  end

  test do
    assert_match "credentialctl version", shell_output("#{bin}/credentialctl --version")
  end
end
